/**
 * รายชื่อรูป blip ทั้งหมดของ RedM / RDR2 (586 แบบ) — ชุดเดียวกับที่ redlookup.com/blips แสดง
 * ข้อมูลจาก rdr3-nativedb-data (GPL-3.0) · รูปเป็นของ Rockstar Games · โหลดรูปผ่าน jsDelivr (ปักไว้ที่ commit เดียว ไม่เปลี่ยนเอง)
 */

export const BLIP_IMAGE_BASE = 'https://cdn.jsdelivr.net/gh/BryceCanyonCounty/rdr3-nativedb-data@0297f047a82c244866dc5936e6abd6d6a6d3c869/blips/images/';

export const BLIP_NAMES = [
  'blip_ambient_bounty_hunter', 'blip_ambient_bounty_hunter_higher', 'blip_ambient_bounty_hunter_lower',
  'blip_ambient_bounty_target', 'blip_ambient_chore', 'blip_ambient_coach', 'blip_ambient_companion',
  'blip_ambient_companion_higher', 'blip_ambient_companion_lower', 'blip_ambient_corpse', 'blip_ambient_death',
  'blip_ambient_eyewitness', 'blip_ambient_gang_leader', 'blip_ambient_herd', 'blip_ambient_herd_straggler',
  'blip_ambient_higher', 'blip_ambient_hitching_post', 'blip_ambient_horse', 'blip_ambient_law',
  'blip_ambient_loan_shark', 'blip_ambient_lower', 'blip_ambient_new', 'blip_ambient_newspaper', 'blip_ambient_npc',
  'blip_ambient_npc_higher', 'blip_ambient_npc_lower', 'blip_ambient_ped_downed', 'blip_ambient_ped_medium',
  'blip_ambient_ped_medium_higher', 'blip_ambient_ped_medium_lower', 'blip_ambient_ped_small',
  'blip_ambient_ped_small_higher', 'blip_ambient_ped_small_lower', 'blip_ambient_quartermaster',
  'blip_ambient_riverboat', 'blip_ambient_secret', 'blip_ambient_sheriff', 'blip_ambient_telegraph',
  'blip_ambient_theatre', 'blip_ambient_tithing', 'blip_ambient_tracking', 'blip_ambient_train', 'blip_ambient_wagon',
  'blip_ambient_warp', 'blip_ammo_arrow', 'blip_ammo_bullets', 'blip_animal', 'blip_animal_dead',
  'blip_animal_quality_01', 'blip_animal_quality_02', 'blip_animal_quality_03', 'blip_animal_skin',
  'blip_app_connected', 'blip_attention', 'blip_bank_debt', 'blip_bath_house', 'blip_camp', 'blip_camp_request',
  'blip_camp_tent', 'blip_campfire', 'blip_campfire_full', 'blip_canoe', 'blip_cash_arthur', 'blip_cash_bag',
  'blip_chest', 'blip_code_center', 'blip_code_center_on_horse', 'blip_code_waypoint', 'blip_deadeye_cross',
  'blip_destroy', 'blip_direction_pointer', 'blip_donate_food', 'blip_event_appleseed', 'blip_event_castor',
  'blip_event_railroad_camp', 'blip_event_riggs_camp', 'blip_fence_building', 'blip_for_sale', 'blip_gang_savings',
  'blip_gang_savings_special', 'blip_grub', 'blip_hat', 'blip_horse_higher', 'blip_horse_lower', 'blip_horse_owned',
  'blip_horse_owned_active', 'blip_horse_owned_bonding_0', 'blip_horse_owned_bonding_1', 'blip_horse_owned_bonding_2',
  'blip_horse_owned_bonding_3', 'blip_horse_owned_bonding_4', 'blip_horse_owned_hitched', 'blip_horse_temp',
  'blip_horse_temp_bonding_0', 'blip_horse_temp_bonding_1', 'blip_horse_temp_bonding_2', 'blip_horse_temp_bonding_3',
  'blip_horse_temp_bonding_4', 'blip_horse_temp_hitched', 'blip_horseshoe_0', 'blip_horseshoe_1', 'blip_horseshoe_2',
  'blip_horseshoe_3', 'blip_horseshoe_4', 'blip_hotel_bed', 'blip_job', 'blip_location_higher', 'blip_location_lower',
  'blip_locked', 'blip_mg_blackjack', 'blip_mg_dominoes', 'blip_mg_dominoes_all3s', 'blip_mg_dominoes_all5s',
  'blip_mg_dominoes_draw', 'blip_mg_drinking', 'blip_mg_fishing', 'blip_mg_five_finger_fillet',
  'blip_mg_five_finger_fillet_burnout', 'blip_mg_five_finger_fillet_guts', 'blip_mg_poker', 'blip_mission_area_beau',
  'blip_mission_area_bill', 'blip_mission_area_bounty', 'blip_mission_area_bronte', 'blip_mission_area_david_geddes',
  'blip_mission_area_dutch', 'blip_mission_area_eagle_flies', 'blip_mission_area_edith', 'blip_mission_area_grays',
  'blip_mission_area_gunslinger_1', 'blip_mission_area_gunslinger_2', 'blip_mission_area_henri',
  'blip_mission_area_hosea', 'blip_mission_area_javier', 'blip_mission_area_john', 'blip_mission_area_kitty',
  'blip_mission_area_leon', 'blip_mission_area_lightning', 'blip_mission_area_loanshark', 'blip_mission_area_mary',
  'blip_mission_area_micah', 'blip_mission_area_rains', 'blip_mission_area_rc', 'blip_mission_area_reverend',
  'blip_mission_area_sadie', 'blip_mission_area_strauss', 'blip_mission_area_trelawney', 'blip_mission_bg',
  'blip_mission_bill', 'blip_mission_bounty', 'blip_mission_camp', 'blip_mission_dutch', 'blip_mission_higher',
  'blip_mission_hosea', 'blip_mission_john', 'blip_mission_lower', 'blip_mission_micah', 'blip_mp_pickup',
  'blip_npc_search', 'blip_objective', 'blip_objective_minor', 'blip_overlay_1', 'blip_overlay_2', 'blip_overlay_3',
  'blip_overlay_4', 'blip_overlay_5', 'blip_overlay_bill', 'blip_overlay_charles', 'blip_overlay_hosea',
  'blip_overlay_javier', 'blip_overlay_john', 'blip_overlay_karen', 'blip_overlay_kieran', 'blip_overlay_lenny',
  'blip_overlay_loanshark', 'blip_overlay_micah', 'blip_overlay_party', 'blip_overlay_pearson', 'blip_overlay_ring',
  'blip_overlay_saddle', 'blip_overlay_sean', 'blip_overlay_strauss', 'blip_overlay_tilly', 'blip_overlay_uncle',
  'blip_overlay_white_1', 'blip_overlay_white_2', 'blip_overlay_white_3', 'blip_overlay_white_4',
  'blip_overlay_white_5', 'blip_photo_studio', 'blip_plant', 'blip_player', 'blip_player_coach', 'blip_poi',
  'blip_post_office', 'blip_post_office_rec', 'blip_proc_bank', 'blip_proc_bounty_poster', 'blip_proc_home',
  'blip_proc_home_locked', 'blip_proc_loanshark', 'blip_proc_track', 'blip_radar_edge_pointer', 'blip_radius_search',
  'blip_rc', 'blip_rc_albert', 'blip_rc_algernon_wasp', 'blip_rc_art', 'blip_rc_calloway', 'blip_rc_chain_gang',
  'blip_rc_charlotte_balfour', 'blip_rc_crackpot', 'blip_rc_deborah', 'blip_rc_gunslinger_1', 'blip_rc_gunslinger_2',
  'blip_rc_gunslinger_3', 'blip_rc_gunslinger_5', 'blip_rc_henri', 'blip_rc_hobbs', 'blip_rc_jeremy_gill',
  'blip_rc_kitty', 'blip_rc_lightning', 'blip_rc_obediah_hinton', 'blip_rc_odd_fellows', 'blip_rc_oh_brother',
  'blip_rc_old_flame', 'blip_rc_slave_catcher', 'blip_rc_war_veteran', 'blip_region_caravan', 'blip_region_hideout',
  'blip_region_hunting', 'blip_robbery_bank', 'blip_robbery_coach', 'blip_robbery_home', 'blip_rpg_overweight',
  'blip_rpg_underweight', 'blip_saddle', 'blip_saloon', 'blip_scm_abe_stablehand', 'blip_scm_abigail',
  'blip_scm_albert_cakes', 'blip_scm_andreas', 'blip_scm_ansel_atherton', 'blip_scm_beau', 'blip_scm_bronte',
  'blip_scm_calderon', 'blip_scm_charles', 'blip_scm_david_geddes', 'blip_scm_dorkins', 'blip_scm_eagle_flies',
  'blip_scm_edith', 'blip_scm_evelyn', 'blip_scm_frances', 'blip_scm_grays', 'blip_scm_jack', 'blip_scm_javier',
  'blip_scm_kieran', 'blip_scm_lenny', 'blip_scm_leon', 'blip_scm_letter', 'blip_scm_marybeth', 'blip_scm_molly_oshea',
  'blip_scm_monroe', 'blip_scm_pearson', 'blip_scm_penelope', 'blip_scm_rains', 'blip_scm_reverend', 'blip_scm_sadie',
  'blip_scm_sean', 'blip_scm_strauss', 'blip_scm_susan', 'blip_scm_tom_dickens', 'blip_scm_trelawney',
  'blip_scm_uncle', 'blip_shop_animal_trapper', 'blip_shop_barber', 'blip_shop_blacksmith', 'blip_shop_butcher',
  'blip_shop_coach_fencing', 'blip_shop_doctor', 'blip_shop_gunsmith', 'blip_shop_horse', 'blip_shop_horse_fencing',
  'blip_shop_horse_saddle', 'blip_shop_market_stall', 'blip_shop_shady_store', 'blip_shop_store', 'blip_shop_tackle',
  'blip_shop_tailor', 'blip_shop_train', 'blip_shop_trainer', 'blip_stable', 'blip_summer_cow', 'blip_summer_feed',
  'blip_summer_guard', 'blip_summer_horse', 'blip_supplies_ammo', 'blip_supplies_food', 'blip_supplies_health',
  'blip_supply_icon_ammo', 'blip_supply_icon_food', 'blip_supply_icon_health', 'blip_swap', 'blip_taxidermist',
  'blip_time_of_day', 'blip_town', 'blip_weapon', 'blip_weapon_bow', 'blip_weapon_cannon', 'blip_weapon_dynamite',
  'blip_weapon_gatling', 'blip_weapon_handgun', 'blip_weapon_longarm', 'blip_weapon_melee', 'blip_weapon_molotov',
  'blip_weapon_shotgun', 'blip_weapon_sniper', 'blip_weapon_throwable', 'blip_weapon_throwing_knife',
  'blip_weapon_tomahawk', 'blip_weapon_torch', 'blip_adversary_large', 'blip_adversary_medium', 'blip_adversary_small',
  'blip_ambient_bounty_hunter_wagon', 'blip_ambient_crate', 'blip_ambient_delivery', 'blip_ambient_hot_target',
  'blip_ambient_hunter', 'blip_ambient_king', 'blip_ambient_marked_for_death', 'blip_ambient_posse_deputy',
  'blip_ambient_posse_deputy_higher', 'blip_ambient_posse_deputy_lower', 'blip_ambient_posse_leader',
  'blip_ambient_posse_leader_higher', 'blip_ambient_posse_leader_lower', 'blip_ambient_tugboat', 'blip_ambient_vip',
  'blip_bag_capture', 'blip_bag_defend', 'blip_ball', 'blip_bolt', 'blip_business_moonshine', 'blip_code_center_glow',
  'blip_code_center_glow_alpha', 'blip_decision', 'blip_gold', 'blip_gunslinger', 'blip_health',
  'blip_hire_camp_follower', 'blip_honor_bad', 'blip_honor_good', 'blip_job_board', 'blip_moonshine',
  'blip_moonshine_still', 'blip_moonshine_vat', 'blip_mp_attack_target', 'blip_mp_base', 'blip_mp_base_1',
  'blip_mp_base_10', 'blip_mp_base_11', 'blip_mp_base_12', 'blip_mp_base_13', 'blip_mp_base_14', 'blip_mp_base_15',
  'blip_mp_base_16', 'blip_mp_base_2', 'blip_mp_base_3', 'blip_mp_base_4', 'blip_mp_base_5', 'blip_mp_base_6',
  'blip_mp_base_7', 'blip_mp_base_8', 'blip_mp_base_9', 'blip_mp_base_a', 'blip_mp_base_b', 'blip_mp_base_c',
  'blip_mp_base_d', 'blip_mp_base_e', 'blip_mp_base_f', 'blip_mp_base_g', 'blip_mp_base_h', 'blip_mp_base_i',
  'blip_mp_base_j', 'blip_mp_beast', 'blip_mp_bounty_dead', 'blip_mp_bounty_hunter_introduction',
  'blip_mp_butcher_table', 'blip_mp_cash_checkpoint', 'blip_mp_coach_escort', 'blip_mp_coach_intercept',
  'blip_mp_coach_recover', 'blip_mp_coach_smuggle', 'blip_mp_collector_map', 'blip_mp_deadeye',
  'blip_mp_defend_target', 'blip_mp_deliver_target', 'blip_mp_elimination_large', 'blip_mp_elimination_medium',
  'blip_mp_elimination_small', 'blip_mp_featured', 'blip_mp_flag', 'blip_mp_game_animal_protection',
  'blip_mp_game_hill', 'blip_mp_game_magnificent_four', 'blip_mp_game_multi_target', 'blip_mp_game_race_canoe',
  'blip_mp_game_race_horse', 'blip_mp_game_runaway_train', 'blip_mp_game_treasure_hunt', 'blip_mp_game_vip',
  'blip_mp_gun_for_hire', 'blip_mp_gun_rush', 'blip_mp_gun_rush_team', 'blip_mp_job_exclusive',
  'blip_mp_job_exclusive_large', 'blip_mp_job_exclusive_small', 'blip_mp_location_a', 'blip_mp_location_b',
  'blip_mp_location_c', 'blip_mp_location_d', 'blip_mp_location_e', 'blip_mp_location_f', 'blip_mp_location_g',
  'blip_mp_location_h', 'blip_mp_location_i', 'blip_mp_location_j', 'blip_mp_location_k', 'blip_mp_location_l',
  'blip_mp_location_m', 'blip_mp_location_n', 'blip_mp_location_o', 'blip_mp_location_p', 'blip_mp_location_q',
  'blip_mp_location_r', 'blip_mp_location_s', 'blip_mp_location_t', 'blip_mp_location_u', 'blip_mp_location_v',
  'blip_mp_location_w', 'blip_mp_location_x', 'blip_mp_location_y', 'blip_mp_location_z',
  'blip_mp_mission_area_braithwaite', 'blip_mp_mission_area_bronte', 'blip_mp_mission_area_clay',
  'blip_mp_mission_area_decision', 'blip_mp_mission_area_gunslinger', 'blip_mp_mission_area_horley',
  'blip_mp_mission_area_jesse', 'blip_mp_mission_area_marshall_tom_davies', 'blip_mp_mission_area_old_man_jones',
  'blip_mp_mission_area_outlaw', 'blip_mp_mission_area_revenge', 'blip_mp_mission_area_robbery',
  'blip_mp_mission_area_samson_finch', 'blip_mp_mission_area_seven', 'blip_mp_mission_braithwaite',
  'blip_mp_mission_bronte', 'blip_mp_mission_clay', 'blip_mp_mission_horley', 'blip_mp_mission_jesse',
  'blip_mp_mission_marshall_tom_davies', 'blip_mp_mission_old_man_jones', 'blip_mp_mission_revenge',
  'blip_mp_mission_robbery', 'blip_mp_mission_samson_finch', 'blip_mp_mission_seven', 'blip_mp_mission_tbd',
  'blip_mp_ordered_item', 'blip_mp_player_wagon', 'blip_mp_player_wagon_hitched', 'blip_mp_playlist_adversary',
  'blip_mp_playlist_adversary_special', 'blip_mp_playlist_capture', 'blip_mp_playlist_exclusive',
  'blip_mp_playlist_freeforall', 'blip_mp_playlist_objective', 'blip_mp_playlist_pve', 'blip_mp_playlist_races',
  'blip_mp_playlist_series_12', 'blip_mp_playlist_series_4', 'blip_mp_playlist_series_8', 'blip_mp_playlist_teamgame',
  'blip_mp_playstyle_defensive', 'blip_mp_playstyle_offensive', 'blip_mp_predator_hunt_mask',
  'blip_mp_role_bounty_hunter_ilo', 'blip_mp_role_collector_ilo', 'blip_mp_role_moonshiner', 'blip_mp_role_trader_ilo',
  'blip_mp_roles_bounty_hunter_lock', 'blip_mp_roles_collector_lock', 'blip_mp_roles_moonshiner_lock',
  'blip_mp_roles_trader_lock', 'blip_mp_roundup', 'blip_mp_rustling', 'blip_mp_shootout', 'blip_mp_spawnpoint',
  'blip_mp_spawnpoint_arrow', 'blip_mp_supplies', 'blip_mp_supplies_base_1', 'blip_mp_supplies_base_10',
  'blip_mp_supplies_base_11', 'blip_mp_supplies_base_12', 'blip_mp_supplies_base_13', 'blip_mp_supplies_base_14',
  'blip_mp_supplies_base_15', 'blip_mp_supplies_base_16', 'blip_mp_supplies_base_2', 'blip_mp_supplies_base_3',
  'blip_mp_supplies_base_4', 'blip_mp_supplies_base_5', 'blip_mp_supplies_base_6', 'blip_mp_supplies_base_7',
  'blip_mp_supplies_base_8', 'blip_mp_supplies_base_9', 'blip_mp_supplies_outline', 'blip_mp_torch',
  'blip_mp_trader_introduction', 'blip_mp_travelling_saleswoman', 'blip_mp_ugc', 'blip_mp_wreckage', 'blip_mvp',
  'blip_ned_kelly_outfit', 'blip_nominated', 'blip_on_call', 'blip_outlaw', 'blip_overlay_6', 'blip_overlay_flag',
  'blip_overlay_white_10', 'blip_overlay_white_11', 'blip_overlay_white_12', 'blip_overlay_white_13',
  'blip_overlay_white_14', 'blip_overlay_white_15', 'blip_overlay_white_16', 'blip_overlay_white_6',
  'blip_overlay_white_7', 'blip_overlay_white_8', 'blip_overlay_white_9', 'blip_ped_1', 'blip_ped_10', 'blip_ped_11',
  'blip_ped_12', 'blip_ped_13', 'blip_ped_14', 'blip_ped_15', 'blip_ped_16', 'blip_ped_17', 'blip_ped_18',
  'blip_ped_19', 'blip_ped_2', 'blip_ped_20', 'blip_ped_21', 'blip_ped_22', 'blip_ped_23', 'blip_ped_24',
  'blip_ped_25', 'blip_ped_26', 'blip_ped_27', 'blip_ped_28', 'blip_ped_29', 'blip_ped_3', 'blip_ped_30',
  'blip_ped_31', 'blip_ped_32', 'blip_ped_4', 'blip_ped_5', 'blip_ped_6', 'blip_ped_7', 'blip_ped_8', 'blip_ped_9',
  'blip_predator', 'blip_product_moonshine', 'blip_quick_weapon_select', 'blip_radar_edge_arrow', 'blip_shop_honor',
  'blip_shop_honor_overlay', 'blip_shop_wardrobe', 'blip_special_series_1', 'blip_special_series_2', 'blip_teamsters',
  'blip_trophy', 'blip_wanted_poster',
];
